'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import './llm.css';
import { averageGenome, createWorld, fitnessSummary, nextGeneration, stepWorld, type SimAgent, type World } from '@agent-genome/simulation';

type Provider = 'ollama' | 'openai-compatible' | 'openai' | 'anthropic';
type LlmConfig = { enabled:boolean; provider:Provider; model:string; apiKey:string; baseUrl:string };
const traitMeta = [
  ['memory','Memory','#64b6ff'],['curiosity','Curiosity','#b688ff'],['risk','Risk','#ffac5c'],['planning','Planning','#7de6a2'],['reflectionFrequency','Reflection','#50e4e7'],['cooperation','Cooperation','#f28bb8'],
] as const;
const defaultConfig:LlmConfig={enabled:false,provider:'ollama',model:'llama3.2',apiKey:'',baseUrl:'http://localhost:11434'};

function Bar({value,color}:{value:number;color:string}) { return <span className="bar"><i style={{width:`${value*10}%`,background:color}}/></span>; }
function GenomeBars({agent}:{agent:SimAgent}) { return <div className="traits">{traitMeta.map(([key,label,color])=><div className="trait" key={key}><span>{label}</span><Bar value={agent.genome[key]} color={color}/><b>{agent.genome[key]}</b></div>)}</div>; }
export default function Exhibit() {
 const canvasRef=useRef<HTMLCanvasElement>(null), worldRef=useRef<World>(createWorld()), last=useRef(performance.now()), uiTick=useRef(0);
 const [world,setWorld]=useState(worldRef.current),[selected,setSelected]=useState<SimAgent|null>(null),[running,setRunning]=useState(true),[speed,setSpeed]=useState(1),[mutation,setMutation]=useState(8),[seconds,setSeconds]=useState(45),[complete,setComplete]=useState(false),[config,setConfig]=useState(defaultConfig),[reflecting,setReflecting]=useState(false),[llmStatus,setLlmStatus]=useState('LLM OFF · deterministic world active');
 const stats=useMemo(()=>fitnessSummary(world.agents),[world]);
 useEffect(()=>{let frame=0;const draw=(now:number)=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d')!,rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio;if(canvas.width!==rect.width*ratio){canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0)}const w=rect.width,h=rect.height,dt=Math.min(.05,(now-last.current)/1000);last.current=now;
   if(running&&!complete){stepWorld(worldRef.current,dt*speed);uiTick.current+=dt;if(uiTick.current>.45){setWorld({...worldRef.current,agents:[...worldRef.current.agents]});uiTick.current=0;}}
   const bg=ctx.createRadialGradient(w*.52,h*.46,1,w*.52,h*.46,Math.max(w,h)*.7);bg.addColorStop(0,'#0e1c2b');bg.addColorStop(.5,'#07101b');bg.addColorStop(1,'#03070d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(111,168,202,.06)';ctx.lineWidth=1;for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
   for(const r of worldRef.current.resources.filter(r=>r.available)){const x=r.x/100*w,y=r.y/100*h;ctx.beginPath();ctx.arc(x,y,6+Math.sin(now*.002+x)*2,0,7);ctx.fillStyle='rgba(116,239,202,.75)';ctx.fill();ctx.beginPath();ctx.arc(x,y,18,0,7);ctx.strokeStyle='rgba(116,239,202,.12)';ctx.stroke()}for(const hzd of worldRef.current.hazards){const x=hzd.x/100*w,y=hzd.y/100*h;ctx.beginPath();ctx.arc(x,y,14+Math.sin(now*.003+x)*4,0,7);ctx.strokeStyle='rgba(244,93,105,.28)';ctx.stroke()}
   for(const a of worldRef.current.agents){const x=a.position.x/100*w,y=a.position.y/100*h,r=5+Math.sin(now*.004+a.hue)*1.5,gr=ctx.createRadialGradient(x,y,1,x,y,24);gr.addColorStop(0,`hsla(${a.hue},90%,75%,.8)`);gr.addColorStop(.3,`hsla(${a.hue},80%,55%,.42)`);gr.addColorStop(1,`hsla(${a.hue},80%,55%,0)`);ctx.fillStyle=gr;ctx.beginPath();ctx.arc(x,y,24,0,7);ctx.fill();ctx.fillStyle=`hsl(${a.hue},75%,62%)`;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.fillStyle='#eaffff';ctx.beginPath();ctx.arc(x+r*.18,y-r*.2,1.4,0,7);ctx.fill();if(selected?.id===a.id){ctx.beginPath();ctx.arc(x,y,15,0,7);ctx.strokeStyle='#e8f6ff';ctx.stroke()}}
   frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[running,complete,speed,selected]);
 useEffect(()=>{if(!running||complete)return;const timer=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);setComplete(true);return 0}return s-1}),1000);return()=>clearInterval(timer)},[running,complete]);
 const select=(event:React.MouseEvent<HTMLCanvasElement>)=>{const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*100,y=(event.clientY-rect.top)/rect.height*100;const agent=worldRef.current.agents.reduce<{agent:SimAgent|null;dist:number}>((best,a)=>{const d=Math.hypot(a.position.x-x,a.position.y-y);return d<best.dist?{agent:a,dist:d}:best},{agent:null,dist:5}).agent;if(agent)setSelected({...agent});};
 const reset=()=>{worldRef.current=createWorld();setWorld(worldRef.current);setSelected(null);setSeconds(45);setComplete(false);setRunning(true)};
 const evolve=()=>{worldRef.current=nextGeneration(worldRef.current,mutation/100);setWorld(worldRef.current);setSelected(null);setSeconds(45);setComplete(false);setRunning(true)};
 const runReflection=async()=>{if(!selected||!config.enabled)return;setReflecting(true);setLlmStatus('Calling LangGraph reflection workflow…');try{const response=await fetch('/api/reflect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({config:{provider:config.provider,model:config.model,apiKey:config.apiKey||undefined,baseUrl:config.baseUrl||undefined},input:{goal:selected.goal,fitness:selected.fitness,memories:selected.memories,genome:selected.genome}})});const result=await response.json();if(!response.ok)throw new Error(result.error);const current=worldRef.current.agents.find(a=>a.id===selected.id)!;for(const [trait,delta] of Object.entries(result.adjustments||{})){if(trait in current.genome)current.genome[trait as keyof typeof current.genome]=Math.max(1,Math.min(10,current.genome[trait as keyof typeof current.genome]+Number(delta)))}current.reflection=result.reflection;setSelected({...current});setWorld({...worldRef.current,agents:[...worldRef.current.agents]});setLlmStatus(`Reflection completed via ${config.provider}`)}catch(error){setLlmStatus(error instanceof Error?error.message:'Reflection failed')}finally{setReflecting(false)}};
 const average=averageGenome(world.agents);
 return <main><header><div className="brand"><span className="specimen">◉</span><div><h1>AGENT <em>GENOME</em></h1><p>AN EVOLUTIONARY INTELLIGENCE EXHIBIT</p></div></div><div className="cycle"><span>OBSERVE</span><i/> <span>PLAN</span><i/> <span className="active">ACT</span><i/> <span>REFLECT</span><i/> <span>EVOLVE</span></div><div className="status"><b className={running?'live':''}/>{running?'SIMULATION LIVE':'SIMULATION PAUSED'}</div></header>
 <section className="stage"><canvas ref={canvasRef} onClick={select}/><div className="world-label"><b>THE PETRI FIELD</b><span>resources, hazards, and fitness are simulated live</span></div><aside className="evolution"><div className="eyebrow">SPECIES TELEMETRY</div><div className="generation"><span>GENERATION</span><strong>{String(world.generation).padStart(2,'0')}</strong><small>00: {String(seconds).padStart(2,'0')} REMAINING</small></div><div className="metrics"><div><b>{world.agents.length}</b><span>POPULATION</span></div><div><b>{stats.average.toFixed(1)}</b><span>AVG FITNESS</span></div><div><b>{stats.best.toFixed(1)}</b><span>BEST FITNESS</span></div></div><div className="subhead">AVERAGE EXPRESSION</div>{traitMeta.map(([key,label,color])=><div className="trait" key={key}><span>{label}</span><Bar value={average[key]} color={color}/><b>{average[key]}</b></div>)}</aside>
 {selected&&<aside className="inspector"><button onClick={()=>setSelected(null)}>×</button><div className="eyebrow">ORGANISM SPECIMEN</div><h2>{selected.id}</h2><div className="identity"><span style={{background:`hsl(${selected.hue},75%,62%)`}}/> Generation {world.generation} · Fitness <b>{selected.fitness.toFixed(1)}</b></div><div className="subhead">GENETIC EXPRESSION</div><GenomeBars agent={selected}/><div className="subhead">CURRENT INTENT</div><p className="intent">{selected.goal}</p><div className="subhead">MEMORY ({selected.memories.length}/20)</div><p className="reflection">{selected.memories.length?selected.memories.map(m=>m.action).join(' · '):'No completed events yet.'}</p><div className="subhead">LANGGRAPH REFLECTION</div><p className="reflection">“{selected.reflection}”</p><button className="reflect-button" disabled={!config.enabled||reflecting} onClick={runReflection}>{reflecting?'REFLECTING…':'RUN REFLECTION'}</button><div className="lineage"><span>PARENT LINEAGE</span><b>{selected.parents.length?selected.parents.join('  +  '):'FOUNDER ORGANISM'}</b></div></aside>}
 <aside className="llm"><div className="eyebrow">OPTIONAL LLM REFLECTION</div><label><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/> Enable real LLM calls</label><select value={config.provider} onChange={e=>setConfig({...config,provider:e.target.value as Provider,baseUrl:e.target.value==='ollama'?'http://localhost:11434':e.target.value==='openai-compatible'?'http://localhost:1234/v1':''})}><option value="ollama">Ollama</option><option value="openai-compatible">LM Studio / OpenAI-compatible</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><input value={config.model} placeholder="Model name" onChange={e=>setConfig({...config,model:e.target.value})}/>{config.provider!=='anthropic'&&<input value={config.baseUrl} placeholder="Base URL" onChange={e=>setConfig({...config,baseUrl:e.target.value})}/>} {(config.provider==='openai'||config.provider==='anthropic'||config.provider==='openai-compatible')&&<input type="password" value={config.apiKey} placeholder="API key (not persisted)" onChange={e=>setConfig({...config,apiKey:e.target.value})}/>}<small>{llmStatus}</small></aside></section>
 <footer><div className="controls"><button onClick={()=>setRunning(!running)} className="play">{running?'Ⅱ  PAUSE':'▶  RESUME'}</button><button onClick={reset}>↺ RESET</button><button onClick={evolve}>✦ NEXT GENERATION</button></div><label>MUTATION RATE <b>{mutation}%</b><input type="range" min="1" max="25" value={mutation} onChange={e=>setMutation(+e.target.value)}/></label><label>SIMULATION SPEED <b>{speed.toFixed(1)}×</b><input type="range" min="0.5" max="3" step="0.5" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><div className="credit"><a href="https://harishkotra.me" target="_blank" rel="noreferrer">BUILT BY HARISH KOTRA</a> · <a href="https://dailybuild.xyz" target="_blank" rel="noreferrer">OTHER BUILDS ↗</a></div></footer>
 {complete&&<div className="transition"><div><span className="eyebrow">GENERATION {world.generation} COMPLETE</span><h3>Strategies leave a trace.</h3><div className="changes"><span>AVG FITNESS <b>{stats.average.toFixed(1)}</b></span><span>RESOURCES <b>{world.agents.reduce((n,a)=>n+a.collected,0)} COLLECTED</b></span><span>MUTATION <b>{mutation}%</b></span></div><button onClick={evolve}>BEGIN GENERATION {world.generation+1} →</button></div></div>}</main>;
}
